name: CI
on: [pull_request]

jobs:
  glsl-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl
        run: |
          cd $GITHUB_WORKSPACE/glsl
          cargo build --verbose
      - name: Test glsl
        run: |
          cd $GITHUB_WORKSPACE/glsl
          cargo test --verbose

  glsl-tree-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl-tree
        run: |
          cd $GITHUB_WORKSPACE/glsl-tree
          cargo build --verbose

  glsl-quasiquote-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Switch to nightly Rust
        run: rustup default nightly
      - name: Build glsl-quasiquote
        run: |
          cd $GITHUB_WORKSPACE/glsl-quasiquote
          cargo build --verbose
      - name: Test glsl-quasiquote
        run: |
          cd $GITHUB_WORKSPACE/glsl-quasiquote
          cargo test --verbose

  glsl-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl
        run: |
          cd $GITHUB_WORKSPACE/glsl
          cargo build --verbose
      - name: Test glsl
        run: |
          cd $GITHUB_WORKSPACE/glsl
          cargo test --verbose

  glsl-tree-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl-tree
        run: |
          cd $GITHUB_WORKSPACE/glsl-tree
          cargo build --verbose

  glsl-quasiquote-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Switch to nightly Rust
        run: rustup default nightly
      - name: Build glsl-quasiquote
        run: |
          cd $GITHUB_WORKSPACE/glsl-quasiquote
          cargo build --verbose
      - name: Test glsl-quasiquote
        run: |
          cd $GITHUB_WORKSPACE/glsl-quasiquote
          cargo test --verbose

  glsl-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl
        run: |
          cd $env:GITHUB_WORKSPACE\glsl
          cargo build --verbose
      - name: Test glsl
        run: |
          cd $env:GITHUB_WORKSPACE\glsl
          cargo test --verbose

  glsl-tree-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cargo update
        run: cargo update
      - name: Build glsl-tree
        run: |
          cd $env:GITHUB_WORKSPACE\glsl-tree
          cargo build --verbose

  glsl-quasiquote-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Switch to nightly Rust
        run: rustup default nightly
      - name: Build glsl-quasiquote
        run: |
          cd $env:GITHUB_WORKSPACE\glsl-quasiquote
          cargo build --verbose
      - name: Test glsl-quasiquote
        run: |
          cd $env:GITHUB_WORKSPACE\glsl-quasiquote
          cargo test --verbose

  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ensure code is correctly formatted
        run: cargo fmt -- --check
